### ISSUE TITLE
Zeex compiler patch?

### ISSUE THREAD

**Issue by PatchwerkQWER** [Southclaws/SIF#13]
Hi,

I have question, is SIF fully compatible with zeex compiler patch? 

Cheers @Southclaw

**Comment by Southclaw** [comment]
I've never tested this, but it doesn't do anything complicated so it should be. The only thing that should worry you is YSI, I'm not sure how well that plays with Zeex' compiler.

**Comment by r4sheed** [comment]
Debug include not working with zeex compiler.

**Comment by Southclaws** [comment]
It might be related to the new YSI `___(x)` variadic syntax. Some time soon I'll update the unit tests for this and get CI set up with Zeex compiler via sampctl.

**Comment by r4sheed** [comment]
yes we talked about this at sampforum.  waiting for the update :)
